# Generated by Django 3.0.7 on 2020-06-21 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResizeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'never started'), ('processing', 'processing'), ('done', 'done')], default='not_started', max_length=15, verbose_name='Статус обработки задачи')),
                ('target_width', models.PositiveSmallIntegerField(verbose_name='Ширина для ресайза')),
                ('target_height', models.PositiveSmallIntegerField(verbose_name='Высота для ресайза')),
                ('img', models.ImageField(upload_to='', verbose_name='Файл картинки')),
            ],
        ),
    ]
